### ISSUE TITLE
Play All

### ISSUE THREAD

**Issue by Engineer152** [Engineer152/yagpdb-sb-music#2]
Add in play all command which will queue up all songs. Check if yag is already in VC otherwise check if user is in VC, then start queue.

Possibly add in flag to shuffle all before adding to the queue.

Add in a repeat at the end? Or wait for play all command to be re issued.

**Comment by SpecialEliteSNP** [comment]
Still want that shuffle or repeat flag? If not, you can close this since I believe that the command works?

**Comment by Engineer152** [comment]
This is closed, it works correctly.
